class AppConstants {}

//ACTIONS
AppConstants.ACTION_OPEN_CLOSE_APP_DRAWER = 'ACTION_OPEN_CLOSE_APP_DRAWER';
AppConstants.ACTION_SHOW_MESSAGE = 'ACTION_SHOW_MESSAGE';
AppConstants.ACTION_BROKER_SETTINGS_CHANGE = 'ACTION_BROKER_SETTINGS_CHANGE';
AppConstants.ACTION_DELETE_BROKER_SETTINGS = 'ACTION_DELETE_BROKER_SETTINGS';
AppConstants.ACTION_ADD_PUBLISHER_BUTTON_CLICK = 'ACTION_ADD_PUBLISHER_BUTTON_CLICK';
AppConstants.ACTION_REMOVE_PUBLISHER_BUTTON_CLICK = 'ACTION_REMOVE_PUBLISHER_BUTTON_CLICK';
AppConstants.ACTION_ADD_SUBSCRIBER_BUTTON_CLICK = 'ACTION_ADD_SUBSCRIBER_BUTTON_CLICK';
AppConstants.ACTION_REMOVE_SUBSCRIBER_BUTTON_CLICK = 'ACTION_REMOVE_SUBSCRIBER_BUTTON_CLICK';
AppConstants.ACTION_PUBLISH_MESSAGE_TO_TOPIC = 'ACTION_PUBLISH_MESSAGE_TO_TOPIC';
AppConstants.ACTION_SUBSCRIBE_TO_TOPIC = 'ACTION_SUBSCRIBE_TO_TOPIC';
AppConstants.ACTION_UN_SUBSCRIBE_TO_TOPIC = 'ACTION_UN_SUBSCRIBE_TO_TOPIC';

//EVENTS
AppConstants.EVENT_OPEN_CLOSE_APP_DRAWER = 'EVENT_OPEN_CLOSE_APP_DRAWER';
AppConstants.EVENT_SHOW_MESSAGE = 'EVENT_SHOW_MESSAGE';
AppConstants.EVENT_BROKER_SETTINGS_CHANGED = 'EVENT_BROKER_SETTINGS_CHANGED';
AppConstants.EVENT_SUBSCRIBER_DATA = 'EVENT_SUBSCRIBER_DATA';

//PAGE LINKS
AppConstants.PAGE_URL_ADD_EDIT_CLIENT_BROKER_SETTINGS = '#/addedit';
AppConstants.PAGE_URL_CLIENT_CONNECTION_DETAILS = '#/broker/';

//WORKER COMMANDS
AppConstants.WORKER_CMD_SAVE_BROKER_SETTINGS = 'WORKER_CMD_SAVE_BROKER_SETTINGS';
AppConstants.WORKER_CMD_GET_ALL_BROKER_SETTINGS = 'WORKER_CMD_GET_ALL_BROKER_SETTINGS';
AppConstants.WORKER_CMD_DELETE_BROKER_SETTINGS = 'WORKER_CMD_DELETE_BROKER_SETTINGS';
AppConstants.WORKER_CMD_BROKER_RECONNECT = 'WORKER_CMD_BROKER_RECONNECT';
AppConstants.WORKER_CMD_BROKER_END_CONNECTION = 'WORKER_CMD_BROKER_END_CONNECTION';
AppConstants.WORKER_CMD_BROKER_PUBLISH_MESSAGE = 'WORKER_CMD_BROKER_PUBLISH_MESSAGE';
AppConstants.WORKER_CMD_SUBSCRIBE_TO_TOPIC = 'WORKER_CMD_SUBSCRIBE_TO_TOPIC';
AppConstants.WORKER_CMD_UN_SUBSCRIBE_TO_TOPIC = 'WORKER_CMD_UN_SUBSCRIBE_TO_TOPIC';

//WORKER EVENTS
AppConstants.WORKER_EVENT_ALL_BROKER_SETTINGS_DATA = 'WORKER_EVENT_ALL_BROKER_SETTINGS_DATA';
AppConstants.WORKER_EVENT_BROKER_CONNECTION_STATE = 'WORKER_EVENT_BROKER_CONNECTION_STATE';
AppConstants.WORKER_EVENT_MESSAGE_RECEIVED_FOR_TOPIC = 'WORKER_EVENT_MESSAGE_RECEIVED_FOR_TOPIC';

//CONSTANTS
AppConstants.ONLINE = 'ONLINE';
AppConstants.OFFLINE = 'OFFLINE';
AppConstants.CLOSE = 'CLOSE';
AppConstants.ERROR = 'ERROR';

//SUPPORTED CLIENTS
AppConstants.WEB_APP = 'WEB_APP';
AppConstants.CHROME_APP = 'CHROME_APP';
AppConstants.CLIENT_TYPE = AppConstants.CHROME_APP; //WEB,CHROME_APP

export default AppConstants;
