class AppConstants {}

//ACTIONS
AppConstants.ACTION_OPEN_CLOSE_MENU = 'ACTION_OPEN_CLOSE_MENU';
AppConstants.ACTION_SELECT_MENU_ITEM = 'ACTION_SELECT_MENU_ITEM';
AppConstants.ACTION_SAVE_BROKER_SETTINGS = 'ACTION_SAVE_BROKER_SETTINGS';

AppConstants.ACTION_DELETE_BROKER_SETTINGS = 'ACTION_DELETE_BROKER_SETTINGS';
AppConstants.ACTION_ADD_PUBLISHER_BUTTON_CLICK = 'ACTION_ADD_PUBLISHER_BUTTON_CLICK';
AppConstants.ACTION_REMOVE_PUBLISHER_BUTTON_CLICK = 'ACTION_REMOVE_PUBLISHER_BUTTON_CLICK';
AppConstants.ACTION_ADD_SUBSCRIBER_BUTTON_CLICK = 'ACTION_ADD_SUBSCRIBER_BUTTON_CLICK';
AppConstants.ACTION_REMOVE_SUBSCRIBER_BUTTON_CLICK = 'ACTION_REMOVE_SUBSCRIBER_BUTTON_CLICK';
//ACTIONS
AppConstants.EVENT_OPEN_CLOSE_MENU = 'EVENT_OPEN_CLOSE_MENU';
AppConstants.EVENT_SELECT_MENU_ITEM = 'EVENT_SELECT_MENU_ITEM';
AppConstants.EVENT_BROKER_SETTINGS_CHANGED = 'EVENT_BROKER_SETTINGS_CHANGED';


//MENU ID'S
AppConstants.MENU_ADD_BROKER = 'MENU_ADD_BROKER';

export default AppConstants;
