class CommonConstants {}

//APP
CommonConstants.APP_VERSION = '0.2.2';
CommonConstants.PLATFORM_WEB_APP = 'WEB_APP';
CommonConstants.PLATFORM_CHROME_APP = 'CHROME_APP';
CommonConstants.PLATFORM_ELECTRON_APP = 'ELECTRON_APP';

//ACTIONS
CommonConstants.ACTION_OPEN_CLOSE_APP_LEFT_DRAWER = 'ACTION_OPEN_CLOSE_APP_LEFT_DRAWER';
CommonConstants.ACTION_SHOW_MESSAGE_TO_USER = 'ACTION_SHOW_MESSAGE_TO_USER';

//EVENTS
CommonConstants.EVENT_OPEN_CLOSE_APP_LEFT_DRAWER = 'EVENT_OPEN_CLOSE_APP_LEFT_DRAWER';
CommonConstants.EVENT_SHOW_MESSAGE_TO_USER = 'EVENT_SHOW_MESSAGE_TO_USER';

//WORKER COMMANDS
CommonConstants.WORKER_CMD_GET_ALL = 'WORKER_CMD_GET_ALL';
CommonConstants.WORKER_CMD_SAVE = 'WORKER_CMD_SAVE';
CommonConstants.WORKER_CMD_DELETE = 'WORKER_CMD_DELETE';
CommonConstants.WORKER_EVENT_DATA = 'WORKER_EVENT_DATA';

//ALERT TYPE
CommonConstants.ALERT_SUCCESS = 'ALERT_SUCCESS';

//ALERT TYPE
CommonConstants.SERVICE_TYPE_MQTT_CLIENTS = 'SERVICE_TYPE_MQTT_CLIENTS';
CommonConstants.SERVICE_TYPE_MQTT_LOAD = 'SERVICE_TYPE_MQTT_LOAD';

export default CommonConstants;